server:
  port: 8080
spring:
  # redis
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
  # sql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum?serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  # rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    stream:
      username: guest
      password: guest
    virtual-host: /
    publisher-confirm-type: correlated # 交换机确认
    publisher-returns: true # 队列确认
    listener:
      direct:
        acknowledge-mode: manual # 手动确认ack信息
  # jackson
  jackson:
    time-zone: Asia/Shanghai  # 指定时区

  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 不开启驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.lisan.forumbackend.controller
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
#  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志 
  is-log: true